version: '3'

services:

  news-app:
    image: gguidini/news-searcher:latest
    volumes:
      - static_volume:/usr/src/app/static  # <-- bind the static volume
      - media_volume:/usr/src/app/media  # <-- bind the media volume
    networks:
      - nginx_network

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/usr/src/app/static  # <-- bind the static volume
      - media_volume:/usr/src/app/media  # <-- bind the media volume
    depends_on:
      - news-app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume: 
  media_volume:  