version: '3'
  services:
    nginx:
      image: nginx:latest
      container_name: nginx-4-news
      ports:
        - "80:8000"   # I like working on 80 since you don't need to specify and looking neat on URL
      volumes:
        - ./:/
        - ./nginx/nginx.conf:/etc/nginx/conf.d
      depends_on:
        - web
    
    web:
      build: .
      container_name: news-searcher
      command: gunicorn news_searcher.wsgi -b 0.0.0.0:8000 --workers 3"
      expose:
        - "8000"